# Config for Stalebot, limited to only `issues`
only: issues

# Issues config
issues:
  daysUntilStale: 60
  daysUntilClose: 7

  # Limit the number of actions per hour, from 1-30. Default is 30
  limitPerRun: 30

  # Issues with these labels will never be considered stale
  exemptLabels:
    - kind/enhancement
    - kind/feature
    - kind/question
    - kind/style
    - kind/workaround
    - bug/need-confirmation
    - bug/confirmed
    - status/discuss
  
  # Only issues with all of these labels are checked if stale. Defaults to `[]` (disabled)
  onlyLabels: []

  # Set to true to ignore issues in a project (defaults to false)
  exemptProjects: true
  # Set to true to ignore issues in a milestone (defaults to false)
  exemptMilestones: true
  # Set to true to ignore issues with an assignee (defaults to false)
  exemptAssignees: true

  # Label to use when marking an issue as stale
  staleLabel: status/stale

  # Comment to post when marking an issue as stale. Set to `false` to disable
  markComment: >
    This issue has been marked as stale as it has not had recent activity, 
    it will be closed if no further activity occurs in the next 7 days.
    If you believe that it has been incorrectly labelled as stale, 
    leave a comment and the label will be removed.

  # Comment to post when removing the stale label.
  # unmarkComment: >
  #   Your comment here.

  # Comment to post when closing a stale issue. Set to `false` to disable
  closeComment: >
    Since no further activity has appeared on this issue it will be closed.
    If you believe that it has been incorrectly closed, leave a comment
    and mention @itsconquest. One of our staff will then review the issue.
    
    Note - If it is an old bug report, make sure that it is reproduceable in the
    latest version of Portainer as it may have already been fixed.
    